// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5swTxliWC3qkgwNHiXCGp1YtBFmILFHs',
    appId: '1:376094989733:web:58b8dc73767e7b307f1c4c',
    messagingSenderId: '376094989733',
    projectId: 'fir-auth-a15be',
    authDomain: 'fir-auth-a15be.firebaseapp.com',
    storageBucket: 'fir-auth-a15be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIlWrZegTX_PdD1ay44V3BSRpfaReY_MQ',
    appId: '1:376094989733:android:384f3d8e1e62c3747f1c4c',
    messagingSenderId: '376094989733',
    projectId: 'fir-auth-a15be',
    storageBucket: 'fir-auth-a15be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ojVIMUACW5JxR3F2qO6qeT07cq7dovE',
    appId: '1:376094989733:ios:1133da91685c4d817f1c4c',
    messagingSenderId: '376094989733',
    projectId: 'fir-auth-a15be',
    storageBucket: 'fir-auth-a15be.appspot.com',
    androidClientId: '376094989733-41saqkl0pcojvkgbpp8u6tubloifoc2b.apps.googleusercontent.com',
    iosClientId: '376094989733-kiaj7e1fgj9b72m1vp0793imm43g121p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ojVIMUACW5JxR3F2qO6qeT07cq7dovE',
    appId: '1:376094989733:ios:1133da91685c4d817f1c4c',
    messagingSenderId: '376094989733',
    projectId: 'fir-auth-a15be',
    storageBucket: 'fir-auth-a15be.appspot.com',
    androidClientId: '376094989733-41saqkl0pcojvkgbpp8u6tubloifoc2b.apps.googleusercontent.com',
    iosClientId: '376094989733-kiaj7e1fgj9b72m1vp0793imm43g121p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTesting',
  );
}
